apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowfield.fullname" . }}-media
  labels: {{- include "knowfield.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.media.storageClass }}
  storageClassName: {{ .Values.media.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.media.size }}
