apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowfield.fullname" . }}
  labels: {{- include "knowfield.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "knowfield.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
